COMMENT =           Python module for using INI-style files

MODPY_EGG_VERSION = 0.4
REVISION =          0
DISTNAME =          iniparse-${MODPY_EGG_VERSION}
PKGNAME =           py-iniparse-${MODPY_EGG_VERSION}
CATEGORIES =        devel
HOMEPAGE =          http://code.google.com/p/iniparse/
MAINTAINER =        David Cantrell <david.l.cantrell@gmail.com>

MASTER_SITES =      http://iniparse.googlecode.com/files/

MODULES =           lang/python

PKG_ARCH =          *

# MIT
PERMIT_PACKAGE_CDROM = Yes
PERMIT_PACKAGE_FTP = Yes
PERMIT_DISTFILES_CDROM = Yes
PERMIT_DISTFILES_FTP = Yes

.include <bsd.port.mk>
